# Generated by Django 5.2.5 on 2025-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_instructor_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
